#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Sun Nov 10 12:42:30 2024
#


import wx

# begin wxGlade: dependencies
# end wxGlade
from datetime import datetime
import os
# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        self.last_emg_recording_path = None
        self.output_dir_path = None
        self.default_output_path = False
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((450, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.nt1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nt1, "Record the data")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.nt1, wx.ID_ANY, "Record the data")
        label_2.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_3.Add(label_2, 0, 0, 0)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.nt1, wx.ID_ANY, "Select the data sources")
        label_3.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_7.Add(label_3, 0, wx.ALL, 4)

        sizer_8 = wx.GridSizer(1, 4, 0, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)

        self.radio_btn_1 = wx.RadioButton(self.nt1, wx.ID_ANY, "EMG", style=wx.RB_SINGLE)
        sizer_8.Add(self.radio_btn_1, 0, wx.ALL, 4)

        self.radio_btn_2 = wx.RadioButton(self.nt1, wx.ID_ANY, "IMU", style=wx.RB_SINGLE)
        sizer_8.Add(self.radio_btn_2, 0, wx.ALL, 4)

        self.button_6 = wx.Button(self.nt1, wx.ID_ANY, "Select sensors\n")
        sizer_8.Add(self.button_6, 0, wx.ALL, 4)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.nt1, wx.ID_ANY, "Select output directory")
        sizer_4.Add(label_1, 0, wx.ALL, 10)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.nt1, wx.ID_ANY, "")
        self.text_ctrl_1.SetMinSize((200, 23))
        sizer_6.Add(self.text_ctrl_1, 0, wx.ALL, 12)

        self.button_5 = wx.Button(self.nt1, wx.ID_ANY, "Confirm directory\n")
        self.button_5.SetMinSize((75, 30))
        sizer_6.Add(self.button_5, 0, wx.ALL, 8)

        self.button_8 = wx.Button(self.nt1, wx.ID_ANY, "Use default")
        sizer_6.Add(self.button_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.nt1, wx.ID_ANY, "Start")
        self.button_2.SetMinSize((60, 25))
        sizer_5.Add(self.button_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.button_1 = wx.Button(self.nt1, wx.ID_ANY, "Pause")
        self.button_1.SetMinSize((60, 25))
        sizer_5.Add(self.button_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.button_3 = wx.Button(self.nt1, wx.ID_ANY, "Renew\n")
        self.button_3.SetMinSize((60, 25))
        sizer_5.Add(self.button_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.button_4 = wx.Button(self.nt1, wx.ID_ANY, "End\n")
        self.button_4.SetMinSize((60, 25))
        sizer_5.Add(self.button_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.nt2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nt2, "Present the data")

        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.nt2, wx.ID_ANY, ""), wx.VERTICAL)

        label_4 = wx.StaticText(sizer_9.GetStaticBox(), wx.ID_ANY, "Present the data")
        label_4.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_9.Add(label_4, 0, 0, 0)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_12, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(sizer_9.GetStaticBox(), wx.ID_ANY, "Signal processing operations")
        sizer_12.Add(label_5, 0, 0, 0)

        sizer_12.Add((0, 0), 0, 0, 0)

        label_7 = wx.StaticText(sizer_9.GetStaticBox(), wx.ID_ANY, "Select the data sources")
        label_7.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_9.Add(label_7, 0, wx.ALL, 4)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)

        self.radio_btn_3 = wx.RadioButton(sizer_9.GetStaticBox(), wx.ID_ANY, "EMG", style=wx.RB_SINGLE)
        sizer_10.Add(self.radio_btn_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        self.radio_btn_4 = wx.RadioButton(sizer_9.GetStaticBox(), wx.ID_ANY, "IMU", style=wx.RB_SINGLE)
        sizer_10.Add(self.radio_btn_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        self.button_7 = wx.Button(sizer_9.GetStaticBox(), wx.ID_ANY, "Select sensors\n")
        sizer_10.Add(self.button_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        sizer_10.Add((0, 0), 0, 0, 0)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(sizer_11, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(sizer_9.GetStaticBox(), wx.ID_ANY, "Select the source of the presented data")
        sizer_11.Add(label_6, 0, wx.ALL, 8)

        self.combo_box_1 = wx.ComboBox(sizer_9.GetStaticBox(), wx.ID_ANY, choices=["Visualise current recording session", "Visualise last recording session", "Select the file from operating system", ""], style=wx.CB_DROPDOWN)
        sizer_11.Add(self.combo_box_1, 0, wx.ALL, 8)

        self.nt3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nt3, "Retransmission")

        self.nt2.SetSizer(sizer_9)

        self.nt1.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.button_5.Bind(wx.EVT_BUTTON, self.on_confirm_pressed)
        self.button_8.Bind(wx.EVT_BUTTON, self.on_default_pressed)
        self.button_2.Bind(wx.EVT_BUTTON, self.on_start_pressed)
        self.button_4.Bind(wx.EVT_BUTTON, self.on_end_pressed)
        # end wxGlade

    def on_confirm_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        if not self.default_output_path:
            path = self.text_ctrl_1.GetValue()
            normalized_path = os.path.normpath(path)
        else:
            path = './data_records'
            normalized_path = os.path.abspath(path)

        if os.path.isabs(normalized_path):
            wx.MessageBox("The path format is valid.", "Validation Result", wx.OK | wx.ICON_INFORMATION)
            self.output_dir_path = normalized_path
        else:
            wx.MessageBox("Invalid path format. Please try again.", "Validation Result", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def on_start_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        current_datetime = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        if self.output_dir_path:
            target_folder = os.path.join(self.output_dir_path, f"recorded_data_{current_datetime}")

            if not os.path.exists(target_folder):
                os.makedirs(target_folder)
            else:
                # Create and show the error message box
                message = f"The target path '{target_folder}' already exists as a file."
                wx.MessageDialog(None, message, "Error", wx.ICON_ERROR | wx.OK)
            print(f"Folder '{target_folder}' has been created.")
            if self.radio_btn_1.GetValue():
                emg_file_path = os.path.join(target_folder, "emg.csv")
                # Sprawdzenie, czy plik już istnieje, aby nie dodać nagłówka ponownie
                file_exists = os.path.isfile(emg_file_path)
                with open(emg_file_path, "a") as self.emg_file:
                    if not file_exists:
                        self.emg_file.write("timestamp,emg_signal\n")

                    self.emg_file.write("start-emg")
                print(f"Data appended to '{emg_file_path}'.")

                # Tworzenie lub dopisywanie do pliku emg.csv, jeśli odpowiedni radiobutton jest zaznaczony
            if self.radio_btn_2.GetValue():
                imu_file_path = os.path.join(target_folder, "imu.csv")
                file_exists = os.path.isfile(imu_file_path)
                with open(imu_file_path, "a") as self.imu_file:
                    if not file_exists:
                        self.imu_file.write("timestamp,acceleration_x,acceleration_y,acceleration_z\n")
                self.emg_file.write("start-imu")
                print(f"Data appended to '{imu_file_path}'.")
        else:
            wx.MessageDialog(self, "No folder was selected!", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()
    def on_end_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        if self.imu_file:
            self.last_imu_recording_path = self.imu_file.name
            self.imu_file.close()
        if self.emg_file:
            self.last_emg_recording_path = self.emg_file.name
            self.emg_file.close()
        self.output_dir_path = None
        self.default_output_path = False
        event.Skip()
    def on_default_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        self.default_output_path = True
        wx.MessageBox("The data will be saved to ./data_records folder", "Validation Result", wx.OK | wx.ICON_INFORMATION)
        self.on_confirm_pressed(event)
        event.Skip()
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
