#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Sun Nov 10 12:42:30 2024
#
import sys

#todo active_sensors rozbić na dwa dla record i dla visualize
# default dir może niew wskazywać poprawnie bo nie pasują slashe
import wx

# begin wxGlade: dependencies
# end wxGlade
import numpy as np
import serial
import time
from datetime import datetime

from matplotlib import pyplot as plt
from wx.lib.agw.aui import right
from wx.lib.agw.shapedbutton import folder
from trigno_data_simulator import TrignoDataSimulator
from pyexpat import features

from libemg.feature_extractor import FeatureExtractor
from libemg.streamers import delsys_streamer
from libemg.data_handler import OnlineDataHandler, OfflineDataHandler, RegexFilter
from dotenv import set_key, load_dotenv, get_key
from pathlib import Path
import os
# begin wxGlade: extracode
# end wxGlade




class CheckListComboPopup(wx.ComboPopup):
    def Init(self):
        self.panel = None
        self.lb = None
        self.parent_combo = None

    def Create(self, parent):
        self.parent_combo = parent.GetParent()
        self.panel = wx.Panel(parent)
        self.panel.SetBackgroundColour(wx.Colour(228, 234, 255))
        self.lb = wx.CheckListBox(self.panel, choices=["ACC", "GYR", "REMAINING"])
        for i in range(self.lb.GetCount()):
            self.lb.Check(i)
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.lb, 1, wx.EXPAND | wx.ALL, 5)
        self.panel.SetSizer(sizer)

        return True

    def GetControl(self):
        return self.panel

    def GetStringValue(self):
        checked = [self.lb.GetString(i) for i in range(self.lb.GetCount()) if self.lb.IsChecked(i)]
        return ", ".join(checked)

    def GetAdjustedSize(self, minWidth, prefHeight, maxHeight):
        item_height = self.lb.GetCharHeight() + 6
        return wx.Size(minWidth, item_height * 3)

class DialogAdjustVisualization(wx.Dialog):
    #zrobione za pomocą wxglade potem usunięte z drzewa by dokonywać modyfikacji w kodzie
    def __init__(self, mode="offline", *args, **kwds):
        self.visualization_additional_data={}
        self.mode = mode
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)

        if self.mode == 'Offline':
            self.SetSize((500, 400))
            self.SetTitle("Additional Data Offline")
        if self.mode == 'Online':
            self.SetSize((500, 200))
            self.SetTitle("Additional Data Online")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_4 = wx.StaticText(self, wx.ID_ANY, "Select the additional visualization parameters")
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_1.Add(label_4, 0, wx.ALL, 15)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 20)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Enter the number of samples used\n for visualization")
        sizer_3.Add(label_1, 0, 0, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self, wx.ID_ANY, "500", min=1, max=1500)
        sizer_3.Add(self.spin_ctrl_1, 0, wx.LEFT, 60)

        if self.mode == "Offline":
            sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
            sizer_1.Add(sizer_4, 1, wx.ALL | wx.EXPAND, 20)

            label_2 = wx.StaticText(self, wx.ID_ANY, "Enter the number of samples in a window")
            sizer_4.Add(label_2, 0, 0, 0)

            self.spin_ctrl_2 = wx.SpinCtrl(self, wx.ID_ANY, "20", min=0, max=1500)
            sizer_4.Add(self.spin_ctrl_2, 0, wx.LEFT, 25)

            sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
            sizer_1.Add(sizer_5, 1, wx.ALL | wx.EXPAND, 20)

            label_3 = wx.StaticText(self, wx.ID_ANY, "Enter the number of samples\n that advances before next window")
            sizer_5.Add(label_3, 0, 0, 0)

            self.spin_ctrl_3 = wx.SpinCtrl(self, wx.ID_ANY, "10", min=0, max=1500)
            sizer_5.Add(self.spin_ctrl_3, 0, wx.LEFT, 60)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        self.button_OK.Bind(wx.EVT_BUTTON, self.on_ok_pressed)
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())
        self.Layout()

    def on_ok_pressed(self, event):
        self.visualization_additional_data["num_samples"] = self.spin_ctrl_1.GetValue()
        if self.mode == "Offline":
            self.visualization_additional_data["window_size"] = self.spin_ctrl_2.GetValue()
            self.visualization_additional_data["window_increment"] = self.spin_ctrl_3.GetValue()
        self.EndModal(wx.ID_OK)
        event.Skip()

class FeaturesDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        self.selected_features = []
        # begin wxGlade: FeaturesDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Features dialog")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Select features")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_1.Add(label_1, 0, wx.ALL, 12)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 30)

        self.choice_1 = wx.Choice(self, wx.ID_ANY, choices=["None", "MAV", "ZC", "SSC", "WL", "LS", "MFL", "MSR", "WAMP", "RMS", "IAV", "DASDV", "VAR", "M0", "M2", "M4", "SPARSI", "IFR", "WLF", "AR", "CC", "LD", "MAVFD", "MAVSLP", "MDF", "MNF", "MPK", "SKEW", "KURT", "RMSPHASOR", "PAP", "WLPHASOR", "MZP", "TM", "SM", "SAMPEN", "FUZZYEN", "DFTR", "ISD", "COR", "MDIFF", "MLK", "ACT", "MOB", "COMP", "WENG", "WV", "WWL", "WENT", "MEAN"])
        self.choice_1.SetSelection(0)
        sizer_3.Add(self.choice_1, 0, wx.ALL, 5)

        self.choice_2 = wx.Choice(self, wx.ID_ANY, choices=["None", "MAV", "ZC", "SSC", "WL", "LS", "MFL", "MSR", "WAMP", "RMS", "IAV", "DASDV", "VAR", "M0", "M2", "M4", "SPARSI", "IFR", "WLF", "AR", "CC", "LD", "MAVFD", "MAVSLP", "MDF", "MNF", "MPK", "SKEW", "KURT", "RMSPHASOR", "PAP", "WLPHASOR", "MZP", "TM", "SM", "SAMPEN", "FUZZYEN", "DFTR", "ISD", "COR", "MDIFF", "MLK", "ACT", "MOB", "COMP", "WENG", "WV", "WWL", "WENT", "MEAN"])
        self.choice_2.SetSelection(0)
        sizer_3.Add(self.choice_2, 0, wx.ALL, 5)

        self.choice_3 = wx.Choice(self, wx.ID_ANY, choices=["None", "MAV", "ZC", "SSC", "WL", "LS", "MFL", "MSR", "WAMP", "RMS", "IAV", "DASDV", "VAR", "M0", "M2", "M4", "SPARSI", "IFR", "WLF", "AR", "CC", "LD", "MAVFD", "MAVSLP", "MDF", "MNF", "MPK", "SKEW", "KURT", "RMSPHASOR", "PAP", "WLPHASOR", "MZP", "TM", "SM", "SAMPEN", "FUZZYEN", "DFTR", "ISD", "COR", "MDIFF", "MLK", "ACT", "MOB", "COMP", "WENG", "WV", "WWL", "WENT", "MEAN"])
        self.choice_3.SetSelection(0)
        sizer_3.Add(self.choice_3, 0, wx.ALL, 5)

        self.choice_4 = wx.Choice(self, wx.ID_ANY, choices=["None", "MAV", "ZC", "SSC", "WL", "LS", "MFL", "MSR", "WAMP", "RMS", "IAV", "DASDV", "VAR", "M0", "M2", "M4", "SPARSI", "IFR", "WLF", "AR", "CC", "LD", "MAVFD", "MAVSLP", "MDF", "MNF", "MPK", "SKEW", "KURT", "RMSPHASOR", "PAP", "WLPHASOR", "MZP", "TM", "SM", "SAMPEN", "FUZZYEN", "DFTR", "ISD", "COR", "MDIFF", "MLK", "ACT", "MOB", "COMP", "WENG", "WV", "WWL", "WENT", "MEAN"])
        self.choice_4.SetSelection(0)
        sizer_3.Add(self.choice_4, 0, wx.ALL, 5)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.button_OK.Bind(wx.EVT_BUTTON, self.on_ok_pressed)
        # end wxGlade

    def on_ok_pressed(self, event):  # wxGlade: FeaturesDialog.<event_handler>
        if self.choice_1.GetStringSelection()!="None":
            self.selected_features.append(self.choice_1.GetStringSelection())
        if self.choice_2.GetStringSelection()!="None":
            self.selected_features.append(self.choice_2.GetStringSelection())
        if self.choice_3.GetStringSelection()!="None":
            self.selected_features.append(self.choice_3.GetStringSelection())
        if self.choice_4.GetStringSelection()!="None":
            self.selected_features.append(self.choice_4.GetStringSelection())

        print(f"selected features: {self.selected_features}")
        self.EndModal(wx.ID_OK)
        event.Skip()
# end of class FeaturesDialog
class SensorsDialog(wx.Dialog):
    def __init__(self, mode="visualize",*args, **kwds):
        self.mode = mode
        self.active_sensors = []
        self.metadata_labels = ["Timestamps"]
        # begin wxGlade: SensorsDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Select Sensors")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Select sensors")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 20)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        sizer_3.Add((20, 0), 0, 0, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        self.toggle_btn_1 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 1")
        sizer_4.Add(self.toggle_btn_1, 0, wx.ALL, 4)

        self.toggle_btn_2 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 2")
        sizer_4.Add(self.toggle_btn_2, 0, wx.ALL, 4)

        self.toggle_btn_3 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 3")
        sizer_4.Add(self.toggle_btn_3, 0, wx.ALL, 4)

        self.toggle_btn_4 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 4")
        sizer_4.Add(self.toggle_btn_4, 0, wx.ALL, 4)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        if self.mode == "record":

            self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "Sensor1")
            sizer_7.Add(self.text_ctrl_1, 0, wx.ALL, 4)

            self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "Sensor2")
            sizer_7.Add(self.text_ctrl_2, 0, wx.ALL, 4)

            self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "Sensor3")
            sizer_7.Add(self.text_ctrl_3, 0, wx.ALL, 4)

            self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "Sensor4")
            sizer_7.Add(self.text_ctrl_4, 0, wx.ALL, 4)

        if self.mode == "record":
            sizer_3.Add((120, 20), 0, 0, 0)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

        self.toggle_btn_5 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 5")
        sizer_5.Add(self.toggle_btn_5, 0, wx.ALL, 4)

        self.toggle_btn_6 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 6")
        sizer_5.Add(self.toggle_btn_6, 0, wx.ALL, 4)

        self.toggle_btn_7 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 7")
        sizer_5.Add(self.toggle_btn_7, 0, wx.ALL, 4)

        self.toggle_btn_8 = wx.ToggleButton(self, wx.ID_ANY, "Sensor 8")
        sizer_5.Add(self.toggle_btn_8, 0, wx.ALL, 4)

        if self.mode =="record":
            sizer_6 = wx.BoxSizer(wx.VERTICAL)
            sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

            self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "Sensor5")
            sizer_6.Add(self.text_ctrl_5, 0, wx.ALL, 4)

            self.text_ctrl_6 = wx.TextCtrl(self, wx.ID_ANY, "Sensor6")
            sizer_6.Add(self.text_ctrl_6, 0, wx.ALL, 4)

            self.text_ctrl_7 = wx.TextCtrl(self, wx.ID_ANY, "Sensor7")
            sizer_6.Add(self.text_ctrl_7, 0, wx.ALL, 4)

            self.text_ctrl_8 = wx.TextCtrl(self, wx.ID_ANY, "Sensor8")
            sizer_6.Add(self.text_ctrl_8, 0, wx.ALL, 4)

        sizer_3.Add((20, 0), 0, 0, 0)

        static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.EXPAND | wx.TOP, 18)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.button_OK.Bind(wx.EVT_BUTTON, self.on_ok_pressed)
        # end wxGlade


    def on_ok_pressed(self, event):  # wxGlade: SensorsDialog.<event_handler>
        if self.mode == "record":
            if self.toggle_btn_1.GetValue():
                self.active_sensors.append(0)
                self.metadata_labels.append(self.text_ctrl_1.GetValue())
            if self.toggle_btn_2.GetValue():
                self.active_sensors.append(1)
                self.metadata_labels.append(self.text_ctrl_2.GetValue())
            if self.toggle_btn_3.GetValue():
                self.active_sensors.append(2)
                self.metadata_labels.append(self.text_ctrl_3.GetValue())
            if self.toggle_btn_4.GetValue():
                self.active_sensors.append(3)
                self.metadata_labels.append(self.text_ctrl_4.GetValue())
            if self.toggle_btn_5.GetValue():
                self.active_sensors.append(4)
                self.metadata_labels.append(self.text_ctrl_5.GetValue())
            if self.toggle_btn_6.GetValue():
                self.active_sensors.append(5)
                self.metadata_labels.append(self.text_ctrl_6.GetValue())
            if self.toggle_btn_7.GetValue():
                self.metadata_labels.append(self.text_ctrl_7.GetValue())
                self.active_sensors.append(6)
            if self.toggle_btn_8.GetValue():
                self.metadata_labels.append(self.text_ctrl_8.GetValue())
                self.active_sensors.append(7)
            if not self.validate_metadata():
                self.active_sensors = []
                self.metadata_labels = []
                
            else:
                self.EndModal(wx.ID_OK)
                event.Skip()
        else:
            if self.toggle_btn_1.GetValue():
                self.active_sensors.append(0)
            if self.toggle_btn_2.GetValue():
                self.active_sensors.append(1)
            if self.toggle_btn_3.GetValue():
                self.active_sensors.append(2)
            if self.toggle_btn_4.GetValue():
                self.active_sensors.append(3)
            if self.toggle_btn_5.GetValue():
                self.active_sensors.append(4)
            if self.toggle_btn_6.GetValue():
                self.active_sensors.append(5)
            if self.toggle_btn_7.GetValue():
                self.active_sensors.append(6)
            if self.toggle_btn_8.GetValue():
                self.active_sensors.append(7)
            self.EndModal(wx.ID_OK)
            event.Skip()

    def validate_metadata(self):
        for item in self.metadata_labels:
            if ' ' in item:
                wx.MessageBox("Metadata cannot contain spaces.", "Validation Error", wx.OK | wx.ICON_ERROR)
                return False
        return True
# end of class SensorsDialog
class DialogOffline(wx.Dialog):
    def __init__(self, *args, **kwds):
        # Content of this block not found. Did you rename this class?
        pass

# end of class DialogOffline

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.selected_features = []
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1100, 600))
        self.SetTitle("EMG acquisition and visualisation app")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.nt1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nt1, "Record the data")

        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_21.Add(sizer_2, 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.nt1, wx.ID_ANY, "Record the data")
        label_2.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_3.Add(label_2, 0, wx.LEFT | wx.TOP, 20)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_7, 1, wx.ALL | wx.EXPAND, 40)

        label_3 = wx.StaticText(self.nt1, wx.ID_ANY, "Select the data sources")
        label_3.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_7.Add(label_3, 0, wx.ALL, 4)

        sizer_7.Add((0, 20), 0, 0, 0)

        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(sizer_20, 1, wx.EXPAND, 0)

        self.check_box_1 = wx.CheckBox(self.nt1, wx.ID_ANY, "EMG")
        sizer_20.Add(self.check_box_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        sizer_20.Add((20, 0), 0, 0, 0)

        self.check_box_2 = wx.CheckBox(self.nt1, wx.ID_ANY, "IMU")
        sizer_20.Add(self.check_box_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_4, 1, wx.ALL | wx.EXPAND, 40)

        label_1 = wx.StaticText(self.nt1, wx.ID_ANY, "Select output directory")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_4.Add(label_1, 0, wx.ALL, 10)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.nt1, wx.ID_ANY, "")
        self.text_ctrl_1.SetMinSize((200, 23))
        sizer_6.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 12)

        self.button_5 = wx.Button(self.nt1, wx.ID_ANY, "Confirm directory\n")
        self.button_5.SetMinSize((75, 30))
        sizer_6.Add(self.button_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        self.button_8 = wx.Button(self.nt1, wx.ID_ANY, "Use default\n")
        sizer_6.Add(self.button_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        sizer_21.Add((50, 0), 0, 0, 0)

        self.panel_4 = wx.Panel(self.nt1, wx.ID_ANY)
        self.panel_4.SetMaxSize((500, 400))
        sizer_21.Add(self.panel_4, 1, wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.VERTICAL)

        sizer_8.Add((0, 170), 0, 0, 0)

        self.button_6 = wx.Button(self.panel_4, wx.ID_ANY, "Select sensors\n")
        sizer_8.Add(self.button_6, 0, 0, 0)

        sizer_8.Add((0, 70), 0, 0, 0)

        self.panel_10 = wx.Panel(self.panel_4, wx.ID_ANY)
        self.panel_10.SetBackgroundColour(wx.Colour(228, 234, 255))
        sizer_8.Add(self.panel_10, 1, 0, 0)

        sizer_22 = wx.BoxSizer(wx.VERTICAL)

        label_9 = wx.StaticText(self.panel_10, wx.ID_ANY, "Signal Recording")
        label_9.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_22.Add(label_9, 0, wx.ALL, 10)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22.Add(sizer_5, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_2 = wx.Button(self.panel_10, wx.ID_ANY, "Start")
        self.button_2.SetMinSize((60, 25))
        sizer_5.Add(self.button_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.button_1 = wx.Button(self.panel_10, wx.ID_ANY, "Pause")
        self.button_1.SetMinSize((60, 25))
        self.button_1.Enable(False)
        sizer_5.Add(self.button_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.button_3 = wx.Button(self.panel_10, wx.ID_ANY, "Renew\n")
        self.button_3.SetMinSize((60, 25))
        self.button_3.Enable(False)
        sizer_5.Add(self.button_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        self.button_4 = wx.Button(self.panel_10, wx.ID_ANY, "End\n")
        self.button_4.SetMinSize((60, 25))
        self.button_4.Enable(False)
        sizer_5.Add(self.button_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 15)

        sizer_5.Add((2, 0), 0, 0, 0)

        self.nt2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nt2, "Present the data")

        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.nt2, wx.ID_ANY, ""), wx.VERTICAL)

        label_4 = wx.StaticText(sizer_9.GetStaticBox(), wx.ID_ANY, "Present the data")
        label_4.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_9.Add(label_4, 0, wx.ALL, 20)

        sizer_9.Add((0, 20), 0, 0, 0)

        sizer_30 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_30, 1, wx.EXPAND, 0)

        self.panel_7 = wx.Panel(self.nt2, wx.ID_ANY)
        sizer_30.Add(self.panel_7, 1, wx.EXPAND, 0)

        sizer_33 = wx.BoxSizer(wx.VERTICAL)

        self.panel_8 = wx.Panel(self.panel_7, wx.ID_ANY)
        sizer_33.Add(self.panel_8, 1, wx.EXPAND, 0)

        sizer_34 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_34.Add((40, 20), 0, 0, 0)

        self.panel_9 = wx.Panel(self.panel_8, wx.ID_ANY)
        sizer_34.Add(self.panel_9, 1, wx.EXPAND, 0)

        sizer_35 = wx.BoxSizer(wx.VERTICAL)

        label_6 = wx.StaticText(self.panel_9, wx.ID_ANY, "Select the source of the presented data")
        label_6.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_35.Add(label_6, 0, wx.ALL, 0)

        sizer_35.Add((0, 20), 0, 0, 0)

        self.combo_box_1 = wx.ComboBox(self.panel_9, wx.ID_ANY, choices=["Visualise current data transmission", "Visualise last recording session", "Select the directory from operating system", ""], style=wx.CB_READONLY)
        sizer_35.Add(self.combo_box_1, 0, wx.ALL, 8)

        sizer_35.Add((0, 20), 0, 0, 0)

        self.panel_6 = wx.Panel(self.panel_8, wx.ID_ANY)
        self.panel_6.SetMaxSize((400, 150))
        sizer_34.Add(self.panel_6, 1, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)

        sizer_12.Add((0, 0), 0, 0, 0)

        label_7 = wx.StaticText(self.panel_6, wx.ID_ANY, "Select the data sources")
        label_7.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_12.Add(label_7, 0, wx.ALL, 4)

        sizer_12.Add((0, 20), 0, 0, 0)

        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12.Add(sizer_26, 1, wx.EXPAND, 0)

        self.checkbox_3 = wx.CheckBox(self.panel_6, wx.ID_ANY, "EMG")
        sizer_26.Add(self.checkbox_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        sizer_26.Add((20, 0), 0, 0, 0)

        self.checkbox_4 = wx.CheckBox(self.panel_6, wx.ID_ANY, "IMU")
        sizer_26.Add(self.checkbox_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        sizer_26.Add((40, 0), 0, 0, 0)

        self.button_7 = wx.Button(self.panel_6, wx.ID_ANY, "Select sensors\n")
        sizer_26.Add(self.button_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        label_5 = wx.StaticText(sizer_9.GetStaticBox(), wx.ID_ANY, "Signal processing operations:")
        label_5.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_30.Add(label_5, 0, wx.LEFT, 40)

        sizer_30.Add((0, 20), 0, 0, 0)

        self.panel_container = wx.Panel(self.nt2, wx.ID_ANY)
        sizer_30.Add(self.panel_container, 1, wx.EXPAND | wx.LEFT, 40)

        sizer_13 = wx.BoxSizer(wx.VERTICAL)

        self.panel_2 = wx.Panel(self.panel_container, wx.ID_ANY)
        self.panel_2.SetMaxSize((430, -1))
        sizer_13.Add(self.panel_2, 1, wx.EXPAND, 0)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_12 = wx.Panel(self.panel_2, wx.ID_ANY)
        self.panel_12.SetBackgroundColour(wx.Colour(228, 234, 255))
        sizer_14.Add(self.panel_12, 1, wx.EXPAND, 0)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)

        self.button_acc = wx.ToggleButton(self.panel_12, wx.ID_ANY, " Amplitude\nChannnels Combined")
        sizer_19.Add(self.button_acc, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.button_ht = wx.ToggleButton(self.panel_12, wx.ID_ANY, "Heatmap\n")
        sizer_19.Add(self.button_ht, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        static_line_2 = wx.StaticLine(self.panel_2, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_14.Add(static_line_2, 0, wx.EXPAND, 0)

        self.panel_11 = wx.Panel(self.panel_2, wx.ID_ANY)
        self.panel_11.SetBackgroundColour(wx.Colour(228, 234, 255))
        sizer_14.Add(self.panel_11, 1, wx.EXPAND, 0)

        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)

        self.button_18 = wx.Button(self.panel_11, wx.ID_ANY, "Adjust Online\nVisualisation Parameters")
        sizer_27.Add(self.button_18, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.panel_3 = wx.Panel(self.panel_container, wx.ID_ANY)
        self.panel_3.SetMaxSize((880, -1))
        sizer_13.Add(self.panel_3, 1, wx.EXPAND, 0)

        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_13 = wx.Panel(self.panel_3, wx.ID_ANY)
        self.panel_13.SetBackgroundColour(wx.Colour(228, 234, 255))
        sizer_28.Add(self.panel_13, 1, wx.EXPAND, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)

        self.button_vs = wx.ToggleButton(self.panel_13, wx.ID_ANY, "Visualize Standard\n")
        sizer_15.Add(self.button_vs, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.button_vsf = wx.ToggleButton(self.panel_13, wx.ID_ANY, "Visualize Selected \nFeatures")
        sizer_15.Add(self.button_vsf, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.button_vsd = wx.ToggleButton(self.panel_13, wx.ID_ANY, "Visualize Selected\n Distributions")
        sizer_15.Add(self.button_vsd, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.button_vsds = wx.ToggleButton(self.panel_13, wx.ID_ANY, "Visualize Selected\n Distributions Separately")
        sizer_15.Add(self.button_vsds, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        static_line_1 = wx.StaticLine(self.panel_3, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_28.Add(static_line_1, 0, wx.EXPAND, 0)

        self.panel_14 = wx.Panel(self.panel_3, wx.ID_ANY)
        self.panel_14.SetBackgroundColour(wx.Colour(228, 234, 255))
        sizer_28.Add(self.panel_14, 1, wx.EXPAND, 0)

        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)

        self.button_19 = wx.Button(self.panel_14, wx.ID_ANY, "Adjust Offline\n Visualisation Parameters")
        sizer_29.Add(self.button_19, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.combo_imu = wx.ComboCtrl(self.panel_14, wx.ID_ANY, style=wx.CB_READONLY)

        self.popup = CheckListComboPopup()
        self.combo_imu.SetPopupControl(self.popup)
        self.combo_imu.SetText("Select IMU elements")
        self.combo_imu.SetForegroundColour(wx.Colour(0, 0, 255))
        sizer_29.Add(self.combo_imu, 1, wx.EXPAND, 0)

        self.button_10 = wx.ToggleButton(sizer_9.GetStaticBox(), wx.ID_ANY, "Visualize")
        self.button_10.SetMinSize((100, 40))
        self.button_10.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_9.Add(self.button_10, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 40)

        self.nt3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nt3, "Retransmission")

        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_23.Add(sizer_10, 0, wx.EXPAND | wx.RIGHT, 60)

        label_8 = wx.StaticText(self.nt3, wx.ID_ANY, "Retransmission")
        label_8.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_10.Add(label_8, 0, wx.ALL, 20)

        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10.Add(sizer_25, 1, wx.EXPAND, 0)

        self.button_12 = wx.ToggleButton(self.nt3, wx.ID_ANY, "START/STOP")
        self.button_12.SetMinSize((200, 100))
        self.button_12.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_25.Add(self.button_12, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 150)

        self.panel_5 = wx.Panel(self.nt3, wx.ID_ANY)
        self.panel_5.SetMinSize((500, -1))
        sizer_23.Add(self.panel_5, 1, wx.EXPAND, 0)

        sizer_24 = wx.BoxSizer(wx.VERTICAL)

        bitmap_1 = wx.StaticBitmap(self.panel_5, wx.ID_ANY, wx.Bitmap("./43e30b4a652a6db37f2d35a284168cad.jpg", wx.BITMAP_TYPE_ANY))
        sizer_24.Add(bitmap_1, 0, wx.ALIGN_RIGHT, 0)

        self.panel_5.SetSizer(sizer_24)

        self.nt3.SetSizer(sizer_23)

        self.panel_14.SetSizer(sizer_29)

        self.panel_13.SetSizer(sizer_15)

        self.panel_3.SetSizer(sizer_28)

        self.panel_11.SetSizer(sizer_27)

        self.panel_12.SetSizer(sizer_19)

        self.panel_2.SetSizer(sizer_14)

        self.panel_container.SetSizer(sizer_13)

        self.panel_6.SetSizer(sizer_12)

        self.panel_9.SetSizer(sizer_35)

        self.panel_8.SetSizer(sizer_34)

        self.panel_7.SetSizer(sizer_33)

        self.nt2.SetSizer(sizer_9)

        self.panel_10.SetSizer(sizer_22)

        self.panel_4.SetSizer(sizer_8)

        self.nt1.SetSizer(sizer_21)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.button_5.Bind(wx.EVT_BUTTON, self.on_confirm_pressed)
        self.button_8.Bind(wx.EVT_BUTTON, self.on_default_pressed)
        self.button_6.Bind(wx.EVT_BUTTON, self.on_select_pressed_rec)
        self.button_2.Bind(wx.EVT_BUTTON, self.on_start_pressed)
        self.button_1.Bind(wx.EVT_BUTTON, self.on_pause_pressed)
        self.button_3.Bind(wx.EVT_BUTTON, self.on_renew_pressed)
        self.button_4.Bind(wx.EVT_BUTTON, self.on_end_pressed)
        self.combo_box_1.Bind(wx.EVT_COMBOBOX, self.on_combo_box_element_selected)
        self.button_7.Bind(wx.EVT_BUTTON, self.on_select_pressed_vis)
        self.button_ht.Bind(wx.EVT_TOGGLEBUTTON, self.on_heatmap_pressed)
        self.button_18.Bind(wx.EVT_BUTTON, self.on_adjust_online)
        self.button_vsf.Bind(wx.EVT_TOGGLEBUTTON, self.on_visualize_selected_features)
        self.button_vsd.Bind(wx.EVT_TOGGLEBUTTON, self.on_visualize_slct_dist)
        self.button_vsds.Bind(wx.EVT_TOGGLEBUTTON, self.on_visualize_slct_dist_sep)
        self.button_19.Bind(wx.EVT_BUTTON, self.on_adjust_offline)
        self.button_10.Bind(wx.EVT_TOGGLEBUTTON, self.on_visualize_pressed)
        self.button_12.Bind(wx.EVT_TOGGLEBUTTON, self.on_start_stop_retr)
        # end wxGlade
        self.last_target_folder = None
        self.target_folder = None
        self.output_dir_path = None
        self.default_output_path = False
        self.active_sensors = []
        self.simulator = None
        self.hide_panels()
        self.folder_visualize = None
        self.regex_filters = []
        self.selected_features_heatmap = []
        self.selected_features_dist = []
        self.selected_features_dist_sep = []
        self.selected_features = []
        self.visualization_additional_data = {
            "num_samples": 500,
            "window_size": 20,
            "window_increment": 10
        }
        self.odh_visualize = None
        self.combo_choice = None
        self.streamer_visualize = None
        self.odh_record = None
        self.lock_tabs = False
        self.metadata_labels = []

    def on_page_changing(self, event):
        if self.lock_tabs:
            event.Veto()

    def on_confirm_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        if not self.default_output_path:
            path = self.text_ctrl_1.GetValue()
            normalized_path = os.path.normpath(path)
        else:
            path = './data_records'
            normalized_path = os.path.abspath(path)

        if os.path.isabs(normalized_path) and  os.path.isdir(normalized_path):
            wx.MessageBox("The path format is valid.", "Validation Result", wx.OK | wx.ICON_INFORMATION)
            self.output_dir_path = normalized_path
        else:
            wx.MessageBox("Invalid path format. Please try again.", "Validation Result", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def on_start_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        current_datetime = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        if self.output_dir_path:
            self.target_folder = os.path.join(self.output_dir_path, f"recorded_data_{current_datetime}")

            if not os.path.exists(self.target_folder):
                print(self.target_folder)
                os.makedirs(self.target_folder)
            else:
                # Create and show the error message box
                message = f"The target path '{self.target_folder}' already exists as a file."
                wx.MessageDialog(None, message, "Error", wx.ICON_ERROR | wx.OK)
            print(f"Folder '{self.target_folder}' has been created.")

            if self.check_box_1.GetValue():
                is_emg_used = True
            else:
                is_emg_used = False

            if self.check_box_2.GetValue():
                is_imu_used = True
            else:
                is_imu_used = False

            if is_emg_used:
                self.save_metadata(self.metadata_labels,os.path.join(self.target_folder, 'metadata_emg') )
            if is_imu_used:
                metadata_labels_imu = []
                for item in self.metadata_labels:
                    for i in range(1, 10):
                        if item == "Timestamps":
                            metadata_labels_imu.append(item)
                            break
                        metadata_labels_imu.append(f"{item}.{i}")

                self.save_metadata(metadata_labels_imu,os.path.join(self.target_folder, 'metadata_imu') )

            streamer, sm = delsys_streamer(emg_port = 50043,
                                           aux_port = 50044,
                                           imu = is_imu_used,
                                           emg = is_emg_used,
                                          channel_list=self.active_sensors)
            self.odh_record = OnlineDataHandler(sm)
            self.odh_record.log_to_file(file_path=os.path.join(self.target_folder, '_'))
            self.lock_tabs = True
            self.button_1.Enable(True)
            self.button_2.Enable(False)
            self.button_4.Enable(True)
        else:
            wx.MessageDialog(self, "No folder was selected!", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()
    def on_end_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        set_key(".env", "LAST_TARGET_FOLDER", str(self.target_folder))
        self.last_target_folder = self.target_folder
        self.target_folder = None
        self.output_dir_path = None
        self.default_output_path = False
        self.active_sensors=[]
        self.odh_record.stop_log()
        self.lock_tabs = False
        self.button_4.Enable(False)
        self.button_1.Enable(False)
        self.button_3.Enable(False)
        self.button_2.Enable(True)
        self.check_box_1.SetValue(False)
        self.check_box_2.SetValue(False)
        event.Skip()
    def on_default_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        self.default_output_path = True
        wx.MessageBox("The data will be saved to ./data_records folder", "Validation Result", wx.OK | wx.ICON_INFORMATION)
        self.on_confirm_pressed(event)
        event.Skip()
    def on_select_pressed_rec(self, event):  # wxGlade: MyFrame.<event_handler>
        dialog = SensorsDialog("record",self)
        if dialog.ShowModal() == wx.ID_OK:
            self.active_sensors = dialog.active_sensors
            self.metadata_labels = dialog.metadata_labels
            print(f"active sensors: {self.active_sensors}")

        event.Skip()
    def on_select_pressed_vis(self, event):  # wxGlade: MyFrame.<event_handler>
        dialog = SensorsDialog("visualize",self)
        if dialog.ShowModal() == wx.ID_OK:
            self.active_sensors = dialog.active_sensors
            print(f"active sensors: {self.active_sensors}")
        event.Skip()

    def on_start_stop_retr(self, event):  # wxGlade: MyFrame.<event_handler>
        if self.button_12.GetValue():
            self.simulator = TrignoDataSimulator()
            self.simulator.start()
            self.button_12.SetBackgroundColour("light-blue")
        else:
            self.simulator.stop_transmission()
            self.button_12.SetBackgroundColour(wx.Colour(225, 225, 225))

        event.Skip()
    def on_pause_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        self.odh_record.stop_log()
        self.button_1.Enable(False)
        self.button_4.Enable(False)
        self.button_3.Enable(True)
        event.Skip()
    def on_renew_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        self.button_4.Enable(True)
        self.button_1.Enable(True)
        self.button_3.Enable(False)
        self.odh_record.log_to_file(file_path=os.path.join(self.target_folder, '_'))
        event.Skip()
    def on_combo_box_element_selected(self, event):  # wxGlade: MyFrame.<event_handler>
        def choose_dir():
            with wx.DirDialog(None, "Choose directory", defaultPath='./data_records',
                               style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST) as dirDialog:
                if dirDialog.ShowModal() == wx.ID_CANCEL:
                    return None

                try:
                    return dirDialog.GetPath()
                except Exception as e:
                    wx.LogError(f"Error during file selection: {e}")
                    return None

        self.hide_panels()
        self.combo_choice = self.combo_box_1.GetStringSelection()

        if self.combo_choice == "Select the directory from operating system":
            wx.MessageBox("Be aware that after saving to file, the channel numbers may not match the original ones."
                          " The channel number now stands for the number of data column"
                          " (not counting timestamps column)", "Channels msg", wx.OK | wx.ICON_INFORMATION)
            self.panel_3.Show()
            self.panel_3.Raise()
            self.folder_visualize = choose_dir()
            if self.folder_visualize:
                print(f"Selected dir: {self.folder_visualize}")
            else:
                wx.MessageBox("You need to select dir","Select Dir", wx.OK | wx.ICON_INFORMATION)
                event.Skip()
                return

        if self.combo_choice == "Visualise last recording session":
            wx.MessageBox("Be aware that after saving to file, the channel numbers may not match the original ones."
                          " The channel number now stands for the number of data column"
                          " (not counting timestamps column)", "Channels msg", wx.OK | wx.ICON_INFORMATION)
            try:
                self.folder_visualize = get_key( str(Path(".env")), "LAST_TARGET_FOLDER")
                if self.folder_visualize is not None:
                    print(f"The last target folder value is present inside the .env: {self.folder_visualize}")
                else:
                    wx.MessageBox("The last target folder value is not present inside the .env",".env missing key", wx.OK | wx.ICON_INFORMATION)
                    event.Skip()
                    return

            except Exception:
                wx.MessageBox(".env doesn't exist", ".env missing", wx.OK | wx.ICON_INFORMATION)
                event.Skip()
                return
            self.panel_3.Show()
            self.panel_3.Raise()

        if self.combo_choice == "Visualise current data transmission":
            self.panel_2.Show()
            self.panel_2.Raise()

        self.panel_container.Layout()
        self.Layout()

        event.Skip()
    def on_visualize_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        if self.button_10.GetValue():
            self.regex_filters = []
            self.lock_tabs = True

            if self.checkbox_3.GetValue() and self.checkbox_4.GetValue():
                is_emg_used = True
                is_imu_used = True

            elif self.checkbox_3.GetValue() and not self.checkbox_4.GetValue():
                is_emg_used = True
                is_imu_used = False
            elif self.checkbox_4.GetValue() and not self.checkbox_3.GetValue():
                is_emg_used = False
                is_imu_used = True

            else:
                is_emg_used = False
                is_imu_used = False

            if self.combo_choice == "Select the directory from operating system" or self.combo_choice == "Visualise last recording session":
                if self.button_vs.GetValue():
                    if is_emg_used:
                        plt.figure()
                        feature_set_dict, fe = self.create_visualization_parameters_offline(['MEAN'],  "emg", "Standard")
                        fe.visualize(feature_set_dict)
                    if is_imu_used:
                        plt.figure()
                        feature_set_dict, fe = self.create_visualization_parameters_offline(['MEAN'],  "imu", "Standard")
                        fe.visualize(feature_set_dict)
                if self.button_vsf.GetValue():
                    if is_emg_used:
                        plt.figure()
                        feature_set_dict, fe = self.create_visualization_parameters_offline(self.selected_features, "emg")
                        fe.visualize(feature_set_dict)
                    if is_imu_used:
                        plt.figure()
                        feature_set_dict, fe = self.create_visualization_parameters_offline(self.selected_features,
                                                                                            "imu")
                        fe.visualize(feature_set_dict)
                if self.button_vsd.GetValue():
                    if is_emg_used:
                        feature_set_dict, fe = self.create_visualization_parameters_offline(self.selected_features_dist, "emg")
                        fe.visualize_all_distributions(feature_set_dict)
                    if is_imu_used:
                        feature_set_dict, fe = self.create_visualization_parameters_offline(self.selected_features_dist, "imu")
                        fe.visualize_all_distributions(feature_set_dict)
                if self.button_vsds.GetValue():
                    if is_emg_used:
                        feature_set_dict, fe = self.create_visualization_parameters_offline(self.selected_features_dist_sep, "emg")
                        fe.visualize_single_distributions(feature_set_dict,render=True)
                    if is_imu_used:
                        feature_set_dict, fe = self.create_visualization_parameters_offline(self.selected_features_dist_sep, "imu")
                        fe.visualize_single_distributions(feature_set_dict,render=True)

            elif self.combo_choice == "Visualise current data transmission":
                self.streamer_visualize, sm = delsys_streamer(emg_port=50043,
                                               aux_port=50044,
                                               imu=is_imu_used,
                                               emg=is_emg_used,
                                               channel_list=self.active_sensors)
                self.odh_visualize = OnlineDataHandler(sm)

                if self.button_acc.GetValue():
                    self.odh_visualize.visualize(self.visualization_additional_data["num_samples"], block=False)

                if self.button_ht.GetValue():
                    self.odh_visualize.visualize_heatmap(self.visualization_additional_data["num_samples"],self.selected_features_heatmap)

        else:
            self.lock_tabs = False
            if self.combo_choice == "Visualise current data transmission":
                self.odh_visualize.stop_visualize()
                self.streamer_visualize.signal.set()
                self.button_ht.SetValue(False)
                self.button_acc.SetValue(False)

            else:
                self.button_vs.SetValue(False)
                self.button_vsf.SetValue(False)
                self.button_vsd.SetValue(False)
                self.button_vsds.SetValue(False)

            self.selected_features_heatmap = []
            self.selected_features_dist = []
            self.selected_features_dist_sep = []
            self.selected_features = []
            self.folder_visualize = None
            self.visualization_additional_data = {
                "num_samples": 500,
                "window_size": 20,
                "window_increment": 10
            }
            self.active_sensors = []
            self.checkbox_3.SetValue(False)
            self.checkbox_4.SetValue(False)
            self.hide_panels()
            self.combo_box_1.SetSelection(3)
            self.combo_choice = None

        event.Skip()
    def on_select_features_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        if event.GetEventObject().GetValue():
            dialog = FeaturesDialog(self)
            if dialog.ShowModal() == wx.ID_OK:
                return dialog.selected_features
        return []


    def hide_panels(self):
        self.panel_2.Hide()
        self.panel_3.Hide()

    def on_adjust(self, mode):
        dialog = DialogAdjustVisualization(mode, self)
        if dialog.ShowModal() == wx.ID_OK:
            self.visualization_additional_data = dialog.visualization_additional_data
            print(f"additional data: {self.visualization_additional_data}")
    def on_adjust_offline(self, event):  # wxGlade: MyFrame.<event_handler>
        self.on_adjust("Offline")
        event.Skip()
    def on_adjust_online(self, event):  # wxGlade: MyFrame.<event_handler>
        self.on_adjust("Online")
        event.Skip()
    def on_heatmap_pressed(self, event):  # wxGlade: MyFrame.<event_handler>
        if event.GetEventObject().GetValue():
            self.selected_features_heatmap = self.on_select_features_pressed(event)
        event.Skip()
    
    def on_visualize_slct_dist(self, event):  # wxGlade: MyFrame.<event_handler>
        if event.GetEventObject().GetValue():
            self.selected_features_dist = self.on_select_features_pressed(event)
        event.Skip()
    def on_visualize_selected_features(self, event):  # wxGlade: MyFrame.<event_handler>
        if event.GetEventObject().GetValue():
            self.selected_features = self.on_select_features_pressed(event)
        event.Skip()
    def on_visualize_slct_dist_sep(self, event):  # wxGlade: MyFrame.<event_handler>
        if event.GetEventObject().GetValue():
            self.selected_features_dist_sep = self.on_select_features_pressed(event)
        event.Skip()
# end of class MyFrame
    def transform_channels_for_imu(self,active_sensors):
        channels = []
        for sensor in active_sensors:
            start_channel = (sensor - 1) * 9 + 1
            channels.extend(range(start_channel, start_channel + 9))

        group_map = {
            0: [1, 2, 3],
            1: [4, 5, 6],
            2: [7, 8, 9]
        }
        allowed_channels = set(channels)
        checked = self.popup.lb.GetCheckedItems()

        for group_id, blocked_positions in group_map.items():
            if group_id not in checked:
                allowed_channels &= {
                    ch for ch in channels
                    if (ch - 1) % 9 not in blocked_positions
                }
        return list(allowed_channels)

    def create_visualization_parameters_offline(self, features_list, emg_or_imu, mode=None):




        channels_isolated = [x + 1 for x in self.active_sensors]

        if emg_or_imu == 'emg':
            right_bound =  "emg.csv"
        if emg_or_imu == 'imu':
            right_bound =  "imu.csv"
            channels_isolated = self.transform_channels_for_imu(channels_isolated)
        if emg_or_imu != 'emg' and emg_or_imu != 'imu':
            right_bound = "Unreachable"
        print(channels_isolated)
        ofdh_new = self._create_adjusted_data_handler(right_bound, channels_isolated)
        try:
            if mode == 'Standard':
                windows, _ = ofdh_new.parse_windows(3, 3)
            else:
                windows, _ = ofdh_new.parse_windows(self.visualization_additional_data["window_size"],
                                                    self.visualization_additional_data["window_increment"])
        except AttributeError:
            wx.MessageBox("You selected channels not present in the data file",
                          "Invalid Channel Selection",
                          wx.OK | wx.ICON_ERROR)
            return None, FeatureExtractor()
        fe = FeatureExtractor()
        feature_set_dict = fe.extract_features(features_list, windows[:self.visualization_additional_data["num_samples"]])
        return feature_set_dict, fe

    def _create_adjusted_data_handler(self, right_bound, channels_isolated):
        ofdh = OfflineDataHandler()
        regex_filter = RegexFilter(left_bound='/', right_bound=right_bound, values=['_'], description='emg or imu')
        ofdh.get_data(folder_location=self.folder_visualize, regex_filters=[regex_filter], delimiter=' ')
        ofdh_new = ofdh.isolate_channels(channels_isolated)
        return ofdh_new

    @staticmethod
    def save_metadata(metadata, filepath):
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(' '.join(str(element) for element in metadata))

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
